/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form jfrmLogin
     */
    public Login() {
        initComponents();
    }

    private void centrarVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jlblSesion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jsptrUsuario = new javax.swing.JSeparator();
        jlblContraseña = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jpwdContraseña = new javax.swing.JPasswordField();
        jbtnEntrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(440, 560));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblSesion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jlblSesion.setText("INICIAR SESION");
        background.add(jlblSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel2.setText("USUARIO");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jtxtUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jtxtUsuario.setText("Ingrese su nombre de usuario");
        jtxtUsuario.setBorder(null);
        jtxtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtUsuarioMousePressed(evt);
            }
        });
        background.add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 300, 30));
        background.add(jsptrUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 330, 10));

        jlblContraseña.setText("CONTRASEÑA");
        background.add(jlblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 330, 10));

        jpwdContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jpwdContraseña.setText("********");
        jpwdContraseña.setBorder(null);
        jpwdContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpwdContraseñaMousePressed(evt);
            }
        });
        background.add(jpwdContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 330, 30));

        jbtnEntrar.setText("Entrar");
        jbtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEntrarActionPerformed(evt);
            }
        });
        background.add(jbtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andrés Ordóñez\\Documents\\NetBeansProjects\\ProyectoPOOG2\\src\\Imagenes\\LogoClinicTest (3).png")); // NOI18N
        jLabel3.setToolTipText("");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 320, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEntrarActionPerformed
        if (jtxtUsuario.getText().equals("Admin123") && jpwdContraseña.getText().trim().equals("12345678")) {
            Pantalla pr = new Pantalla();
            pr.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jbtnEntrarActionPerformed

    private void jpwdContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpwdContraseñaMousePressed
        if (String.valueOf(jpwdContraseña.getPassword()).equals("********")) {
            jpwdContraseña.setText("");
            jpwdContraseña.setForeground(Color.black);
        }
        if (jtxtUsuario.getText().isEmpty()) {
            jtxtUsuario.setText("Ingrese su nombre de usuario");
            jtxtUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jpwdContraseñaMousePressed

    private void jtxtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtUsuarioMousePressed
        if (jtxtUsuario.getText().equals("Ingrese su nombre de usuario")) {
            jtxtUsuario.setText("");
            jtxtUsuario.setForeground(Color.black);
        }
        if (String.valueOf(jpwdContraseña.getPassword()).isEmpty()) {
            jpwdContraseña.setText("********");
            jpwdContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jtxtUsuarioMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnEntrar;
    private javax.swing.JLabel jlblContraseña;
    private javax.swing.JLabel jlblSesion;
    private javax.swing.JPasswordField jpwdContraseña;
    private javax.swing.JSeparator jsptrUsuario;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
